# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_ENV: development
  APP_PORT: 7000
  APP_NAME: node_clean
  MONGO_USER: root
  MONGO_PW: root
  MONGO_PORT: 27017
  MONGO_DBNAME: node_clean-db
  MONGO_HOST: localhost
  BYCRYPT_SALT: 10
  JWT_SECRET_KEY: secret
  JWT_EXPIRED: 24h
  RATE_LIMIT_MAX: 100
  RATE_LIMIT_MINUTE: 15
  GRPC_PORT: 50051
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - run: make infra
    - run: make test
